import { useState, useEffect, useCallback } from "react";
import { format } from "date-fns";
import {
  FiX,
  FiDownload,
  FiFile,
  FiChevronDown,
  FiRefreshCw,
  FiCalendar,
  FiClock,
  FiUser,
  FiArrowLeft,
} from "react-icons/fi";
import styles from "../DoctorStyle/DayAppointmentsModal.module.css";
import CompleteAppointmentModal from "./CompleteAppointmentModal";

const API_BASE = "http://localhost:8000/api";
const getToken = () => localStorage.getItem("token");

/* ─────────────────────────────────────────────────────────
   API fetch
───────────────────────────────────────────────────────── */
async function fetchAppointments(date, signal) {
  const dateStr = format(date, "yyyy-MM-dd");
  const res = await fetch(`${API_BASE}/appointments?date=${dateStr}`, {
    headers: {
      Authorization: `Bearer ${getToken()}`,
      Accept: "application/json",
    },
    signal,
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const json = await res.json();
  return json.data || [];
}

/* ─────────────────────────────────────────────────────────
   mapAppointment — maps Laravel fields to display shape

   TWO reference numbers:
   • appointment_ref    → always auto-generated by backend model
                          PAC-YYYY-MM-DD-XXXX or PAE-YYYY-MM-DD-XXXX
   • payment_reference  → optional, user-entered GCash/bank ref
───────────────────────────────────────────────────────── */
function mapAppointment(raw) {
  const patient = raw.patient || {};
  const patientName =
    [
      patient.firstName,
      patient.middleInitial ? patient.middleInitial + "." : null,
      patient.lastName,
    ]
      .filter(Boolean)
      .join(" ") ||
    raw.patient_name ||
    "—";

  const doctor = raw.doctor || {};
  const doctorName = doctor.firstName
    ? [
        doctor.firstName,
        doctor.middleInitial ? doctor.middleInitial + "." : null,
        doctor.lastName,
      ]
        .filter(Boolean)
        .join(" ")
    : null;

  const booker = raw.bookedBy || raw.booked_by || {};
  const bookerName = booker.firstName
    ? [booker.firstName, booker.lastName].filter(Boolean).join(" ")
    : null;

  return {
    id: raw.appointment_id,
    appointment_id: raw.appointment_id,

    // Patient
    patientName,
    patientId: raw.patient_id,
    patientDob: patient.dob || null,
    patientSex: patient.sex || null,
    patientContact: patient.contactNo || null,
    patientEmail: patient.email || null,
    patientAddress: patient.address || null,
    patientClassification: patient.patientClassification || null,
    gender: patient.sex || null,

    // Informant
    informantName: raw.informant_name || null,
    informantRelation: raw.informant_relation || null,

    // Schedule
    appointmentDate: raw.appointment_date,
    startTime: raw.start_time,
    endTime: raw.end_time,
    start: new Date(`${raw.appointment_date}T${raw.start_time}:00`),
    end: new Date(`${raw.appointment_date}T${raw.end_time}:00`),

    // Visit / service
    visitType: raw.visit_type || "onsite",
    serviceType: raw.service_type || "",
    paePurpose: raw.pae_purpose || null,
    assessmentPurpose: raw.pae_purpose || null,
    reason: raw.reason_for_consultation || null,

    // Payment
    paymentStatus: raw.payment_status,
    paymentReference: raw.payment_reference || null, // user-entered GCash/bank ref
    receiptPaths:
      raw.receipt_paths || (raw.receipt_path ? [raw.receipt_path] : []),

    // Status
    status: raw.status,

    // Doctor / Booker
    doctorName,
    doctorId: raw.doctor_user_id || null,
    bookerName,
    bookedByUserId: raw.booked_by_user_id,

    // Notes
    notes: raw.notes || null,

    // ── appointment_ref: always auto-generated by the model ──
    //    PAC-YYYY-MM-DD-XXXX  or  PAE-YYYY-MM-DD-XXXX
    appointmentRef: raw.appointment_ref || "—",

    // Title for legacy compat
    title:
      raw.visit_type === "virtual"
        ? "Online Consultation"
        : "Physical Consultation",
  };
}

/* ─────────────────────────────────────────────────────────
   Helpers
───────────────────────────────────────────────────────── */
const toTime12 = (timeStr) => {
  if (!timeStr) return "";
  const [h, m] = timeStr.split(":");
  const hour = parseInt(h);
  return `${hour % 12 || 12}:${m} ${hour >= 12 ? "PM" : "AM"}`;
};

const isPsychAssessment = (s = "") =>
  s.toLowerCase().includes("psychological assessment") ||
  s.toLowerCase().includes("assessment and evaluation");

const isESA = (s = "") =>
  s.toLowerCase().includes("emotional support animal") ||
  s.toLowerCase().includes("esa");
const isInternship = (s = "") => s.toLowerCase().includes("internship");

const getServiceLabel = (appt) => {
  const svc = appt.serviceType || "";
  if (isPsychAssessment(svc) || isESA(svc) || isInternship(svc))
    return "Psychological Assessment and Evaluation";
  return "Psychotherapy and Counseling";
};

const COLORS = {
  purple: "#4D227C",
  blue: "#1e6091",
  red: "#dc2626",
  brown: "#8B4545",
  green: "#2d6a4f",
  amber: "#92400e",
  teal: "#0e7490",
  violet: "#5b21b6",
};

const getDotColor = (appt) => {
  const svc = appt.serviceType || "";
  if (isESA(svc)) return COLORS.teal;
  if (isInternship(svc)) return COLORS.violet;
  if (isPsychAssessment(svc)) {
    const p = (appt.assessmentPurpose || "").toLowerCase();
    if (p.includes("vawc")) return COLORS.red;
    if (p.includes("legal") || p.includes("adoption")) return COLORS.brown;
    if (p.includes("school") || p.includes("academic")) return COLORS.blue;
    if (p.includes("pre-employment") || p.includes("pre_employment"))
      return COLORS.amber;
    return COLORS.green;
  }
  return appt.visitType === "virtual" ? COLORS.blue : COLORS.purple;
};

const purposeBadgeStyle = (p = "") => {
  const l = p.toLowerCase();
  if (l.includes("vawc"))
    return {
      background: "#ede9f6",
      color: "#4D227C",
      border: "1px solid #d8ccf0",
    };
  if (l.includes("legal") || l.includes("adoption"))
    return {
      background: "#fce8e8",
      color: "#8B4545",
      border: "1px solid #f5c6c6",
    };
  if (l.includes("school") || l.includes("academic"))
    return {
      background: "#dbeafe",
      color: "#1e6091",
      border: "1px solid #bfdbfe",
    };
  if (l.includes("work"))
    return {
      background: "#dcfce7",
      color: "#2d6a4f",
      border: "1px solid #bbf7d0",
    };
  if (l.includes("pre-employment") || l.includes("pre_employment"))
    return {
      background: "#fef3c7",
      color: "#92400e",
      border: "1px solid #fde68a",
    };
  return {
    background: "#f3f4f6",
    color: "#6b7280",
    border: "1px solid #e5e7eb",
  };
};

const serviceBadgeStyle = (svc = "") => {
  if (isESA(svc))
    return {
      background: "#cffafe",
      color: "#0e7490",
      border: "1px solid #a5f3fc",
    };
  if (isInternship(svc))
    return {
      background: "#ede9fe",
      color: "#5b21b6",
      border: "1px solid #ddd6fe",
    };
  if (isPsychAssessment(svc))
    return {
      background: "#ede9f6",
      color: "#4D227C",
      border: "1px solid #d8ccf0",
    };
  return {
    background: "#f3f4f6",
    color: "#374151",
    border: "1px solid #e5e7eb",
  };
};

const paymentBadgeStyle = (s = "") => {
  if (s === "paid")
    return {
      background: "#dcfce7",
      color: "#15803d",
      border: "1px solid #bbf7d0",
    };
  if (s === "probono")
    return {
      background: "#dbeafe",
      color: "#1e6091",
      border: "1px solid #bfdbfe",
    };
  return {
    background: "#fef3c7",
    color: "#92400e",
    border: "1px solid #fde68a",
  };
};

const paymentLabel = (s = "") =>
  s === "paid" ? "Paid" : s === "probono" ? "Pro Bono" : "Not Paid";

/* ─────────────────────────────────────────────────────────
   Safe date / time helpers
───────────────────────────────────────────────────────── */
function safeFormatDate(value, fmt = "MMMM d, yyyy") {
  if (!value) return "—";
  try {
    if (value instanceof Date)
      return isNaN(value.getTime()) ? "—" : format(value, fmt);
    // Handle ISO strings like "2005-09-21T00:00:00.000000Z"
    if (typeof value === "string") {
      // Plain date string YYYY-MM-DD
      if (/^\d{4}-\d{2}-\d{2}$/.test(value))
        return format(new Date(value + "T00:00:00"), fmt);
      // ISO datetime string — parse and format
      const d = new Date(value);
      return isNaN(d.getTime()) ? "—" : format(d, fmt);
    }
    const d = new Date(value);
    return isNaN(d.getTime()) ? "—" : format(d, fmt);
  } catch {
    return "—";
  }
}

function safeTime12(value) {
  if (!value) return "—";
  if (typeof value === "string" && /^\d{1,2}:\d{2}/.test(value))
    return toTime12(value);
  if (value instanceof Date && !isNaN(value.getTime())) {
    const h = value.getHours(),
      m = String(value.getMinutes()).padStart(2, "0");
    return `${h % 12 || 12}:${m} ${h >= 12 ? "PM" : "AM"}`;
  }
  return "—";
}

function normalizeAppt(appt) {
  if (!appt) return appt;
  if (appt.appointmentDate && appt.startTime) return appt;

  const start =
    appt.start instanceof Date
      ? appt.start
      : appt.start
        ? new Date(appt.start)
        : null;
  const end =
    appt.end instanceof Date ? appt.end : appt.end ? new Date(appt.end) : null;
  const padT = (d) =>
    d
      ? `${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`
      : null;

  return {
    ...appt,
    appointmentDate: start
      ? `${start.getFullYear()}-${String(start.getMonth() + 1).padStart(2, "0")}-${String(start.getDate()).padStart(2, "0")}`
      : appt.appointmentDate || null,
    startTime: appt.startTime || padT(start),
    endTime: appt.endTime || padT(end),
    visitType:
      appt.visitType ||
      (appt.title?.toLowerCase().includes("online") ? "virtual" : "onsite"),
    serviceType: appt.serviceType || "",
    patientName:
      appt.patientName ||
      [appt.patient?.firstName, appt.patient?.lastName]
        .filter(Boolean)
        .join(" ") ||
      "—",
    status: appt.status || "pending",
    paymentStatus: appt.paymentStatus || appt.payment_status || "not_paid",
    paymentReference: appt.paymentReference || appt.payment_reference || null,
    assessmentPurpose:
      appt.assessmentPurpose || appt.pae_purpose || appt.paePurpose || null,
    reason: appt.reason || appt.reason_for_consultation || null,
    receiptPaths: appt.receiptPaths || appt.receipt_paths || [],
    appointment_id: appt.appointment_id || appt.id,
    appointmentRef: appt.appointmentRef || appt.appointment_ref || "—",
  };
}

/* ─────────────────────────────────────────────────────────
   UI pieces
───────────────────────────────────────────────────────── */
const Badge = ({ style, children }) => (
  <span
    style={{
      display: "inline-flex",
      alignItems: "center",
      padding: "3px 10px",
      borderRadius: 20,
      fontSize: 11.5,
      fontWeight: 600,
      fontFamily: "'Poppins',sans-serif",
      ...style,
    }}
  >
    {children}
  </span>
);

const InfoRow = ({ label, value }) => (
  <div className={styles.infoRow}>
    <span className={styles.infoLabel}>{label}:</span>
    <span className={styles.infoValue}>{value}</span>
  </div>
);

function StatusBadge({ status }) {
  const s = (status || "").toLowerCase();
  const map = {
    pending: {
      color: "#b45309",
      background: "#fef3c7",
      border: "1px solid #fde68a",
      label: "Pending",
    },
    confirmed: {
      color: "#1e6091",
      background: "#dbeafe",
      border: "1px solid #bfdbfe",
      label: "Confirmed",
    },
    completed: {
      color: "#15803d",
      background: "#dcfce7",
      border: "1px solid #bbf7d0",
      label: "Completed",
    },
    cancelled: {
      color: "#dc2626",
      background: "#fce8e8",
      border: "1px solid #f5c6c6",
      label: "Cancelled",
    },
    no_show: {
      color: "#6b7280",
      background: "#f3f4f6",
      border: "1px solid #e5e7eb",
      label: "No Show",
    },
  };
  const st = map[s] || map[s.replace("canceled", "cancelled")];
  if (!st)
    return (
      <span style={{ fontSize: 12, fontWeight: 700, color: "#4d227c" }}>
        {status || "—"}
      </span>
    );
  return (
    <span
      style={{
        fontSize: 12,
        fontWeight: 700,
        padding: "2px 10px",
        borderRadius: 20,
        ...st,
      }}
    >
      {st.label}
    </span>
  );
}

function DrawerAccordion({
  title,
  children,
  defaultOpen = false,
  accentColor = "#4D227C",
}) {
  const [isOpen, setIsOpen] = useState(defaultOpen);
  return (
    <div className={styles.card}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className={styles.accordionHeader}
        style={{
          background: isOpen ? `${accentColor}12` : "#faf7ff",
          borderBottom: isOpen ? `2px solid ${accentColor}` : "none",
        }}
      >
        <span
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            color: accentColor,
            flex: 1,
          }}
        >
          {title}
        </span>
        <FiChevronDown
          size={18}
          style={{
            color: accentColor,
            transition: "transform 0.3s ease",
            transform: isOpen ? "rotate(180deg)" : "rotate(0deg)",
            flexShrink: 0,
          }}
        />
      </button>
      {isOpen && (
        <div
          className={styles.accordionBodyWrapper}
          style={{ borderTop: `2px solid ${accentColor}` }}
        >
          <div className={styles.accordionBody}>{children}</div>
        </div>
      )}
    </div>
  );
}

function ReceiptViewer({ paths = [] }) {
  if (!paths || paths.length === 0) return null;
  return (
    <DrawerAccordion title="Receipt / Proof of Payment" accentColor="#15803d">
      <div style={{ display: "flex", flexWrap: "wrap", gap: "10px" }}>
        {paths.map((path, i) => {
          const url = `http://localhost:8000/storage/${path}`;
          const isPdf = path.toLowerCase().endsWith(".pdf");
          return (
            <a
              key={i}
              href={url}
              target="_blank"
              rel="noopener noreferrer"
              style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                gap: "6px",
                padding: "10px",
                border: "1.5px solid #bbf7d0",
                borderRadius: "10px",
                background: "#f0fdf4",
                textDecoration: "none",
                color: "#15803d",
                fontSize: "11px",
                fontWeight: "600",
                minWidth: "80px",
                transition: "background .15s",
              }}
              onMouseEnter={(e) =>
                (e.currentTarget.style.background = "#dcfce7")
              }
              onMouseLeave={(e) =>
                (e.currentTarget.style.background = "#f0fdf4")
              }
            >
              <FiFile size={22} />
              <span>{isPdf ? "PDF" : `Image ${i + 1}`}</span>
              <span
                style={{
                  fontSize: "10px",
                  color: "#6b7280",
                  display: "flex",
                  alignItems: "center",
                  gap: "3px",
                }}
              >
                <FiDownload size={10} /> View
              </span>
            </a>
          );
        })}
      </div>
    </DrawerAccordion>
  );
}

function LoadingSkeleton() {
  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        gap: "12px",
        padding: "4px 0",
      }}
    >
      {[1, 2].map((i) => (
        <div
          key={i}
          style={{
            borderRadius: "12px",
            overflow: "hidden",
            border: "1px solid #f0eaf8",
          }}
        >
          <div
            style={{
              height: "44px",
              background:
                "linear-gradient(90deg,#f3ecfc 0%,#e8dcf5 50%,#f3ecfc 100%)",
              backgroundSize: "200% 100%",
              animation: "shimmer 1.4s infinite",
            }}
          />
          <div
            style={{
              padding: "16px",
              display: "flex",
              flexDirection: "column",
              gap: "10px",
            }}
          >
            {[80, 60, 70, 50].map((w, j) => (
              <div
                key={j}
                style={{
                  height: "14px",
                  width: `${w}%`,
                  borderRadius: "7px",
                  background:
                    "linear-gradient(90deg,#f3ecfc 0%,#e8dcf5 50%,#f3ecfc 100%)",
                  backgroundSize: "200% 100%",
                  animation: "shimmer 1.4s infinite",
                }}
              />
            ))}
          </div>
        </div>
      ))}
      <style>{`@keyframes shimmer{0%{background-position:200% 0}100%{background-position:-200% 0}}`}</style>
    </div>
  );
}

/* ─────────────────────────────────────────────────────────
   Detail View
───────────────────────────────────────────────────────── */
function DetailView({ appt: rawAppt, onClose, onBack, onRefresh }) {
  const [showCompleteModal, setShowCompleteModal] = useState(false);
  const appt = normalizeAppt(rawAppt);

  const svc = appt.serviceType || "";
  const isAssessment = isPsychAssessment(svc);
  const purpose = appt.assessmentPurpose || "";
  const dotColor = getDotColor(appt);
  const serviceLabel = getServiceLabel(appt);
  const visitLabel =
    appt.visitType === "virtual"
      ? "Virtual Consultation"
      : "Onsite Consultation";
  const dateBadge = safeFormatDate(appt.appointmentDate, "MMM d, yyyy");
  const dateFull = safeFormatDate(appt.appointmentDate, "MMMM d, yyyy");
  const timeDisplay = `${safeTime12(appt.startTime)} – ${safeTime12(appt.endTime)}`;

  // ── FIX: Format DOB properly from ISO string ──
  const formattedDob = appt.patientDob
    ? safeFormatDate(appt.patientDob, "MMMM d, yyyy")
    : null;

  return (
    <>
      <div className={styles.overlay} onClick={onClose}>
        <div className={styles.modal} onClick={(e) => e.stopPropagation()}>
          <div className={styles.modalHeader}>
            <h3 className={styles.modalTitle}>
              <span
                className={styles.clinicDot}
                style={{ backgroundColor: dotColor }}
              />
              Appointment Details
            </h3>
            <div className={styles.modalHeaderRight}>
              <span className={styles.dateBadge}>{dateBadge}</span>

              {/* ── FIX: Back button uses FiArrowLeft icon from react-icons ── */}
              {onBack && (
                <button
                  onClick={onBack}
                  style={{
                    background: "none",
                    border: "1px solid #e2d5f5",
                    borderRadius: "7px",
                    cursor: "pointer",
                    color: "#ffffff",
                    fontSize: "12px",
                    padding: "5px 10px",
                    fontWeight: "600",
                    fontFamily: "'Poppins', sans-serif",
                    display: "inline-flex",
                    alignItems: "center",
                    gap: "5px",
                    lineHeight: 1,
                  }}
                >
                  <FiArrowLeft size={13} />
                
                </button>
              )}

              <button
                className={styles.closeBtn}
                onClick={onClose}
                aria-label="Close"
              >
                <FiX />
              </button>
            </div>
          </div>

          <div className={styles.scrollBody}>
            {/* ── Main info card ── */}
            <section className={styles.card}>
              <div className={styles.cardHeader}>
                <span className={styles.cardHeaderLeft}>
                  <span
                    className={styles.clinicDot}
                    style={{ backgroundColor: dotColor }}
                  />
                  Appointment Information
                </span>
                {/* ── appointment_ref (always present, auto-generated) ── */}
                <span className={styles.referenceNumber}>
                  {appt.appointmentRef}
                </span>
              </div>

              <div className={styles.cardBody}>
                <div className={styles.cardFields}>
                  {/* Appointment Ref highlighted */}
                  <div className={styles.infoRow}>
                    <span className={styles.infoLabel}>Appt. Ref No.:</span>
                    <span
                      style={{
                        fontWeight: 700,
                        color: "#4D227C",
                        fontSize: "13px",
                        fontFamily: "'Courier New',monospace",
                        letterSpacing: "0.04em",
                      }}
                    >
                      {appt.appointmentRef}
                    </span>
                  </div>

                  <InfoRow
                    label="Patient Name"
                    value={appt.patientName || "—"}
                  />

                  {/* ── FIX: DOB formatted properly ── */}
                  {formattedDob && (
                    <InfoRow label="Date of Birth" value={formattedDob} />
                  )}

                  {appt.patientSex && (
                    <InfoRow
                      label="Sex"
                      value={
                        appt.patientSex.charAt(0).toUpperCase() +
                        appt.patientSex.slice(1)
                      }
                    />
                  )}
                  {appt.patientContact && (
                    <InfoRow label="Contact No." value={appt.patientContact} />
                  )}
                  {appt.patientEmail && (
                    <InfoRow label="Email" value={appt.patientEmail} />
                  )}
                  {appt.patientClassification && (
                    <InfoRow
                      label="Classification"
                      value={appt.patientClassification}
                    />
                  )}

                  <div className={styles.infoRow}>
                    <span className={styles.infoLabel}>Appointment Date:</span>
                    <span
                      className={styles.infoValue}
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "5px",
                      }}
                    >
                      <FiCalendar size={13} style={{ color: "#9c7dd4" }} />{" "}
                      {dateFull}
                    </span>
                  </div>

                  <div className={styles.infoRow}>
                    <span className={styles.infoLabel}>Time:</span>
                    <span
                      className={styles.infoValue}
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "5px",
                      }}
                    >
                      <FiClock size={13} style={{ color: "#9c7dd4" }} />{" "}
                      {timeDisplay}
                    </span>
                  </div>

                  <InfoRow label="Visit Type" value={visitLabel} />

                  <div className={styles.infoRow}>
                    <span className={styles.infoLabel}>Service:</span>
                    <Badge style={serviceBadgeStyle(svc)}>{serviceLabel}</Badge>
                  </div>

                  {isAssessment && purpose && (
                    <div className={styles.infoRow}>
                      <span className={styles.infoLabel}>Purpose:</span>
                      <Badge style={purposeBadgeStyle(purpose)}>
                        {purpose}
                      </Badge>
                    </div>
                  )}

                  <div className={styles.infoRow}>
                    <span className={styles.infoLabel}>Payment:</span>
                    <Badge style={paymentBadgeStyle(appt.paymentStatus)}>
                      {paymentLabel(appt.paymentStatus)}
                    </Badge>
                  </div>

                  {/* Payment Reference — shown when paid and reference exists */}
                  {appt.paymentStatus === "paid" && appt.paymentReference && (
                    <div className={styles.infoRow}>
                      <span className={styles.infoLabel}>Payment Ref:</span>
                      <span
                        style={{
                          fontSize: "13px",
                          fontWeight: 600,
                          color: "#166534",
                          fontFamily: "'Courier New',monospace",
                          letterSpacing: "0.04em",
                        }}
                      >
                        {appt.paymentReference}
                      </span>
                    </div>
                  )}

                  <div className={styles.infoRow}>
                    <span className={styles.infoLabel}>Status:</span>
                    <StatusBadge status={appt.status} />
                  </div>

                  {appt.reason && (
                    <div>
                      <div className={styles.complaintLabel}>
                        Reason for Consultation:
                      </div>
                      <div className={styles.complaintBox}>{appt.reason}</div>
                    </div>
                  )}

                  {appt.doctorName && (
                    <div className={styles.infoRow}>
                      <span className={styles.infoLabel}>Assigned Doctor:</span>
                      <span
                        className={styles.infoValue}
                        style={{
                          display: "flex",
                          alignItems: "center",
                          gap: "5px",
                        }}
                      >
                        <FiUser size={13} style={{ color: "#9c7dd4" }} />{" "}
                        {appt.doctorName}
                      </span>
                    </div>
                  )}

                  {appt.informantName && (
                    <>
                      <InfoRow label="Informant" value={appt.informantName} />
                      {appt.informantRelation && (
                        <InfoRow
                          label="Relation"
                          value={appt.informantRelation}
                        />
                      )}
                    </>
                  )}

                  {appt.notes && (
                    <div>
                      <div className={styles.complaintLabel}>
                        Clinical Notes:
                      </div>
                      <div className={styles.complaintBox}>{appt.notes}</div>
                    </div>
                  )}
                </div>
              </div>

              {appt.status !== "completed" && appt.status !== "cancelled" && (
                <div className={styles.cardFooter}>
                  <button
                    className={styles.btnGreen}
                    onClick={() => setShowCompleteModal(true)}
                  >
                    Add Clinical Notes
                  </button>
                </div>
              )}
            </section>

            <ReceiptViewer paths={appt.receiptPaths} />
          </div>
        </div>
      </div>

      <CompleteAppointmentModal
        isOpen={showCompleteModal}
        onClose={() => setShowCompleteModal(false)}
        appt={appt}
        onConfirm={() => {
          setShowCompleteModal(false);
          if (onRefresh) onRefresh();
        }}
      />
    </>
  );
}

/* ─────────────────────────────────────────────────────────
   Appointment Card (list view)
───────────────────────────────────────────────────────── */
function AppointmentCard({ appt, onView }) {
  const svc = appt.serviceType || "";
  const dotColor = getDotColor(appt);
  const serviceLabel = getServiceLabel(appt);
  const purpose = appt.assessmentPurpose || "";
  const visitLabel = appt.visitType === "virtual" ? "Virtual" : "Onsite";

  return (
    <div className={styles.card}>
      <div className={styles.cardHeader}>
        <span className={styles.cardHeaderLeft}>
          <span
            className={styles.clinicDot}
            style={{ backgroundColor: dotColor }}
          />
          {toTime12(appt.startTime)} — {visitLabel} Consultation
        </span>
        <span className={styles.badgeGroup}>
          {purpose && (
            <Badge
              style={{
                ...purposeBadgeStyle(purpose),
                fontSize: 11,
                padding: "2px 9px",
              }}
            >
              {purpose}
            </Badge>
          )}
          {/* ── appointment_ref shown in card header ── */}
          <span className={styles.referenceNumber}>{appt.appointmentRef}</span>
        </span>
      </div>

      <div className={styles.cardBody}>
        <div className={styles.cardFields}>
          <InfoRow label="Patient" value={appt.patientName} />

          <div className={styles.infoRow}>
            <span className={styles.infoLabel}>Time:</span>
            <span className={styles.infoValue}>
              {toTime12(appt.startTime)} – {toTime12(appt.endTime)}
            </span>
          </div>

          <div className={styles.infoRow}>
            <span className={styles.infoLabel}>Service:</span>
            <Badge style={{ ...serviceBadgeStyle(svc), fontSize: 11 }}>
              {serviceLabel}
            </Badge>
          </div>

          {appt.reason && <InfoRow label="Reason" value={appt.reason} />}

          <div className={styles.infoRow}>
            <span className={styles.infoLabel}>Payment:</span>
            <Badge
              style={{ ...paymentBadgeStyle(appt.paymentStatus), fontSize: 11 }}
            >
              {paymentLabel(appt.paymentStatus)}
            </Badge>
          </div>

          {/* ── Payment Reference in list card ── */}
          {appt.paymentStatus === "paid" && appt.paymentReference && (
            <div className={styles.infoRow}>
              <span className={styles.infoLabel}>Payment Ref:</span>
              <span
                style={{
                  fontSize: "12px",
                  fontWeight: 600,
                  color: "#166534",
                  fontFamily: "'Courier New', monospace",
                  letterSpacing: "0.04em",
                }}
              >
                {appt.paymentReference}
              </span>
            </div>
          )}

          <div className={styles.infoRow}>
            <span className={styles.infoLabel}>Status:</span>
            <StatusBadge status={appt.status} />
          </div>

          {appt.doctorName && (
            <InfoRow label="Doctor" value={appt.doctorName} />
          )}
        </div>
      </div>

      <div className={styles.cardFooter}>
        <button className={styles.btnPurple} onClick={() => onView(appt)}>
          View Details
        </button>
      </div>
    </div>
  );
}

/* ─────────────────────────────────────────────────────────
   MAIN COMPONENT
───────────────────────────────────────────────────────── */
function DayAppointmentsModal({ isOpen, onClose, selectedDate }) {
  const [appointments, setAppointments] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [activeAppt, setActiveAppt] = useState(null);

  const loadAppointments = useCallback(async (date, signal) => {
    if (!date) return;
    setLoading(true);
    setError(null);
    try {
      const raw = await fetchAppointments(date, signal);
      setAppointments(raw.map(mapAppointment));
    } catch (e) {
      if (e.name !== "AbortError")
        setError(e.message || "Failed to load appointments.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!isOpen || !selectedDate) return;
    setActiveAppt(null);
    const ctrl = new AbortController();
    loadAppointments(new Date(selectedDate), ctrl.signal);
    return () => ctrl.abort();
  }, [isOpen, selectedDate, loadAppointments]);

  if (!isOpen || !selectedDate) return null;

  const dateObj = new Date(selectedDate);
  const formattedDate = format(dateObj, "MMMM d, yyyy");
  const dayName = format(dateObj, "EEEE");
  const handleRefresh = () => loadAppointments(dateObj);

  if (activeAppt) {
    return (
      <DetailView
        appt={activeAppt}
        onClose={onClose}
        onBack={() => setActiveAppt(null)}
        onRefresh={() => {
          setActiveAppt(null);
          handleRefresh();
        }}
      />
    );
  }

  return (
    <div className={styles.overlay} onClick={onClose}>
      <div className={styles.modal} onClick={(e) => e.stopPropagation()}>
        <div className={styles.modalHeader}>
          <h3 className={styles.modalTitle}>{dayName}'s Appointments</h3>
          <div className={styles.modalHeaderRight}>
            <span className={styles.dateBadge}>{formattedDate}</span>
            <button
              onClick={handleRefresh}
              disabled={loading}
              title="Refresh"
              style={{
                background: "none",
                border: "1px solid #e2d5f5",
                borderRadius: "7px",
                cursor: "pointer",
                color: "#ffffff",
                padding: "5px",
                display: "flex",
                alignItems: "center",
                opacity: loading ? 0.5 : 1,
              }}
            >
              <FiRefreshCw
                size={14}
                style={{
                  animation: loading ? "spin 1s linear infinite" : "none",
                }}
              />
            </button>
            <button
              className={styles.closeBtn}
              onClick={onClose}
              aria-label="Close"
            >
              <FiX />
            </button>
          </div>
        </div>

        <div className={styles.scrollBody}>
          {loading ? (
            <LoadingSkeleton />
          ) : error ? (
            <div style={{ textAlign: "center", padding: "40px 20px" }}>
              <div style={{ fontSize: "32px", marginBottom: "12px" }}>⚠️</div>
              <p
                style={{
                  color: "#dc2626",
                  fontSize: "14px",
                  margin: "0 0 16px",
                  fontFamily: "'Poppins',sans-serif",
                }}
              >
                {error}
              </p>
              <button
                onClick={handleRefresh}
                style={{
                  background: "#4D227C",
                  color: "#fff",
                  border: "none",
                  borderRadius: "8px",
                  padding: "8px 20px",
                  cursor: "pointer",
                  fontSize: "13px",
                  fontWeight: "600",
                  display: "inline-flex",
                  alignItems: "center",
                  gap: "6px",
                }}
              >
                <FiRefreshCw size={13} /> Try Again
              </button>
            </div>
          ) : appointments.length === 0 ? (
            <div
              style={{
                textAlign: "center",
                color: "#9ca3af",
                fontSize: 14,
                padding: "48px 0",
                fontFamily: "'Poppins',sans-serif",
              }}
            >
              <div style={{ fontSize: 40, marginBottom: 12, opacity: 0.3 }}>
                📅
              </div>
              <p style={{ margin: 0 }}>
                No appointments scheduled for this day.
              </p>
            </div>
          ) : (
            <>
              <div
                style={{
                  fontSize: "12px",
                  color: "#9c7dd4",
                  fontWeight: "600",
                  marginBottom: "12px",
                  fontFamily: "'Poppins',sans-serif",
                }}
              >
                {appointments.length} appointment
                {appointments.length !== 1 ? "s" : ""} on {formattedDate}
              </div>
              {appointments.map((appt) => (
                <AppointmentCard
                  key={appt.id}
                  appt={appt}
                  onView={setActiveAppt}
                />
              ))}
            </>
          )}
        </div>
      </div>
      <style>{`@keyframes spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}`}</style>
    </div>
  );
}

export default DayAppointmentsModal;
