export const MOCK_APPOINTMENTS = [
  // ══════════════════════════════════════════════════════════════════════════
  // PROGRAM 1 — Psychotherapy and Counseling (Sessions 1–4, Active)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 1,
    serviceClass: "PAC",
    programId: "PROG-0001",
    bookedBy: "client",
    sessionNumber: 1,
    totalSessions: 10,
    progressionStatus: "Active",
    disclaimerAccepted: true,
    declineReason: null,
    doctorHistory: [{ sessionNumber: 1, doctor: "Almie Buco" }],
    referenceNumber: "PAC-0001-2026-01-05",
    time: "4:00 P.M.",
    date: "January 5, 2026",
    serviceType: "Psychotherapy and Counseling",
    doctor: "Almie Buco",
    type: "Online Consultation",
    status: "Completed",
    patientName: "Juan Dela Cruz",
    classification: "Regular",
    sex: "Male",
    dateOfBirth: "09/01/2003",
    contactNumber: "+63 9XXXXXXXXX",
    email: "example@gmail.com",
    homeAddress: "Cabuyao City",
    paymentMode: "G-Cash",
    receiptUrl: "#",
    referenceNo: "GCash-REF-000001",
    totalAmount: 800,
    proofFile: "receipt_proof.jpg",
    wantsPrintedReport: null,
    employerName: null,
    assessmentPurpose: null,
    travelType: null,
    hasDiagnosis: null,
    diagnosisFile: null,
    schoolName: null,
    program: null,
    company: null,
    docFiles: null,
    reason: "Seeking help for anxiety and stress management.",
  },

  {
    id: 2,
    serviceClass: "PAC",
    programId: "PROG-0001",
    bookedBy: "client",
    sessionNumber: 2,
    totalSessions: 10,
    progressionStatus: "Active",
    disclaimerAccepted: true,
    declineReason: null,
    doctorHistory: [
      { sessionNumber: 1, doctor: "Almie Buco" },
      { sessionNumber: 2, doctor: "Almie Buco" },
    ],
    referenceNumber: "PAC-0002-2026-01-12",
    time: "4:00 P.M.",
    date: "January 12, 2026",
    serviceType: "Psychotherapy and Counseling",
    doctor: "Almie Buco",
    type: "Online Consultation",
    status: "Completed",
    patientName: "Juan Dela Cruz",
    classification: "Regular",
    sex: "Male",
    dateOfBirth: "09/01/2003",
    contactNumber: "+63 9XXXXXXXXX",
    email: "example@gmail.com",
    homeAddress: "Cabuyao City",
    paymentMode: "G-Cash",
    receiptUrl: "#",
    referenceNo: "GCash-REF-000002",
    totalAmount: 800,
    proofFile: "receipt_proof.jpg",
    wantsPrintedReport: null,
    employerName: null,
    assessmentPurpose: null,
    travelType: null,
    hasDiagnosis: null,
    diagnosisFile: null,
    schoolName: null,
    program: null,
    company: null,
    docFiles: null,
    reason: "Seeking help for anxiety and stress management.",
  },

  {
    id: 3,
    serviceClass: "PAC",
    programId: "PROG-0001",
    bookedBy: "client",
    sessionNumber: 3,
    totalSessions: 10,
    progressionStatus: "Active",
    disclaimerAccepted: true,
    declineReason: null,
    doctorHistory: [
      { sessionNumber: 1, doctor: "Almie Buco" },
      { sessionNumber: 2, doctor: "Almie Buco" },
      {
        sessionNumber: 3,
        doctor: "Christine Anne Villamarzo",
        changedBy: "client",
        changeReason: "Patient requested doctor change",
        changeDate: "January 15, 2026",
      },
    ],
    referenceNumber: "PAC-0003-2026-01-19",
    time: "10:00 A.M.",
    date: "January 19, 2026",
    serviceType: "Psychotherapy and Counseling",
    doctor: "Christine Anne Villamarzo",
    type: "Clinic - CMPS",
    status: "Completed",
    patientName: "Juan Dela Cruz",
    classification: "Regular",
    sex: "Male",
    dateOfBirth: "09/01/2003",
    contactNumber: "+63 9XXXXXXXXX",
    email: "example@gmail.com",
    homeAddress: "Cabuyao City",
    paymentMode: "Cash",
    receiptUrl: "#",
    referenceNo: null,
    totalAmount: 800,
    proofFile: "receipt_proof.jpg",
    wantsPrintedReport: null,
    employerName: null,
    assessmentPurpose: null,
    travelType: null,
    hasDiagnosis: null,
    diagnosisFile: null,
    schoolName: null,
    program: null,
    company: null,
    docFiles: null,
    reason: "Seeking help for anxiety and stress management.",
  },

  // ── SESSION 4 — Completed ← para makita ang "Book Next Session" button
  {
    id: 4,
    serviceClass: "PAC",
    programId: "PROG-0001",
    bookedBy: "client",
    sessionNumber: 4,
    totalSessions: 10,
    progressionStatus: "Active",
    disclaimerAccepted: true,
    declineReason: null,
    doctorHistory: [
      { sessionNumber: 1, doctor: "Almie Buco" },
      { sessionNumber: 2, doctor: "Almie Buco" },
      {
        sessionNumber: 3,
        doctor: "Christine Anne Villamarzo",
        changedBy: "client",
        changeReason: "Patient requested doctor change",
        changeDate: "January 15, 2026",
      },
      { sessionNumber: 4, doctor: "Christine Anne Villamarzo" },
    ],
    referenceNumber: "PAC-0004-2026-01-26",
    time: "10:00 A.M.",
    date: "January 26, 2026",
    serviceType: "Psychotherapy and Counseling",
    doctor: "Christine Anne Villamarzo",
    type: "Clinic - CMPS",
    status: "Completed", // ← Completed para lumabas ang Book Next Session
    patientName: "Juan Dela Cruz",
    classification: "Regular",
    sex: "Male",
    dateOfBirth: "09/01/2003",
    contactNumber: "+63 9XXXXXXXXX",
    email: "example@gmail.com",
    homeAddress: "Cabuyao City",
    paymentMode: "Cash",
    receiptUrl: "#",
    referenceNo: null,
    totalAmount: 800,
    proofFile: "receipt_proof.jpg",
    wantsPrintedReport: null,
    employerName: null,
    assessmentPurpose: null,
    travelType: null,
    hasDiagnosis: null,
    diagnosisFile: null,
    schoolName: null,
    program: null,
    company: null,
    docFiles: null,
    reason: "Seeking help for anxiety and stress management.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PROGRAM 2 — Psychiatric Assessment (Discontinued)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 5,
    serviceClass: "PAC",
    programId: "PROG-0002",
    bookedBy: "admin",
    sessionNumber: 1,
    totalSessions: 10,
    progressionStatus: "Discontinued",
    disclaimerAccepted: true,
    declineReason: {
      reason: "Personal reasons",
      note: "Patient opted not to continue after initial session.",
    },
    doctorHistory: [{ sessionNumber: 1, doctor: "Aevon Mustapha" }],
    referenceNumber: "PAE-0005-2026-02-01",
    time: "9:00 A.M.",
    date: "February 1, 2026",
    serviceType: "Psychiatric Assessment",
    doctor: "Aevon Mustapha",
    type: "Clinic - CMPS",
    status: "Completed",
    patientName: "Juan Dela Cruz",
    classification: "Regular",
    sex: "Male",
    dateOfBirth: "09/01/2003",
    contactNumber: "+63 9XXXXXXXXX",
    email: "example@gmail.com",
    homeAddress: "Cabuyao City",
    paymentMode: "G-Cash",
    receiptUrl: "#",
    referenceNo: "GCash-REF-000005",
    totalAmount: 800,
    proofFile: "receipt_proof.jpg",
    wantsPrintedReport: null,
    employerName: null,
    assessmentPurpose: null,
    travelType: null,
    hasDiagnosis: null,
    diagnosisFile: null,
    schoolName: null,
    program: null,
    company: null,
    docFiles: null,
    reason: "Initial psychiatric evaluation.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PROGRAM 3 — Mental Health Certification (On Hold)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 6,
    serviceClass: "PAC",
    programId: "PROG-0003",
    bookedBy: "admin",
    sessionNumber: 1,
    totalSessions: 10,
    progressionStatus: "On Hold",
    disclaimerAccepted: true,
    declineReason: {
      reason: "Schedule conflict",
      note: "Patient requested to pause and reschedule next session at a later date.",
    },
    doctorHistory: [{ sessionNumber: 1, doctor: "C. Malabanan" }],
    referenceNumber: "PAC-0006-2026-02-10",
    time: "1:00 P.M.",
    date: "February 10, 2026",
    serviceType: "Mental Health Certification",
    doctor: "C. Malabanan",
    type: "Clinic - CMPS",
    status: "Completed",
    patientName: "Juan Dela Cruz",
    classification: "Regular",
    sex: "Male",
    dateOfBirth: "09/01/2003",
    contactNumber: "+63 9XXXXXXXXX",
    email: "example@gmail.com",
    homeAddress: "Cabuyao City",
    paymentMode: "G-Cash",
    receiptUrl: "#",
    referenceNo: "GCash-REF-000006",
    totalAmount: 800,
    proofFile: "receipt_proof.jpg",
    wantsPrintedReport: null,
    employerName: null,
    assessmentPurpose: null,
    travelType: null,
    hasDiagnosis: null,
    diagnosisFile: null,
    schoolName: null,
    program: null,
    company: null,
    docFiles: null,
    reason: "Certification for mental health status.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // STANDALONE APPOINTMENTS
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 7,
    serviceClass: "PAC",
    programId: null,
    bookedBy: "client",
    sessionNumber: null,
    totalSessions: null,
    progressionStatus: null,
    disclaimerAccepted: true,
    declineReason: null,
    doctorHistory: null,
    referenceNumber: "PAC-0007-2026-02-21",
    time: "3:00 P.M.",
    date: "February 21, 2026",
    serviceType: "Initial Consultation",
    doctor: "Almie Buco",
    type: "Online Consultation",
    status: "Confirmed",
    patientName: "Juan Dela Cruz",
    classification: "Regular",
    sex: "Male",
    dateOfBirth: "09/01/2003",
    contactNumber: "+63 9XXXXXXXXX",
    email: "example@gmail.com",
    homeAddress: "Cabuyao City",
    paymentMode: "Cash",
    receiptUrl: "#",
    referenceNo: null,
    totalAmount: 800,
    proofFile: "receipt_proof.jpg",
    wantsPrintedReport: null,
    employerName: null,
    assessmentPurpose: null,
    travelType: null,
    hasDiagnosis: null,
    diagnosisFile: null,
    schoolName: null,
    program: null,
    company: null,
    docFiles: null,
    reason: "General consultation.",
  },

  {
    id: 8,
    serviceClass: "PAC",
    programId: null,
    bookedBy: "client",
    sessionNumber: null,
    totalSessions: null,
    progressionStatus: null,
    disclaimerAccepted: true,
    declineReason: null,
    doctorHistory: null,
    referenceNumber: "PAE-0008-2026-01-27",
    time: "10:00 A.M.",
    date: "January 27, 2026",
    serviceType: "Psychiatric Assessment",
    doctor: "Aevon Mustapha",
    type: "Online Consultation",
    status: "Cancelled",
    patientName: "Juan Dela Cruz",
    classification: "Regular",
    sex: "Male",
    dateOfBirth: "09/01/2003",
    contactNumber: "+63 9XXXXXXXXX",
    email: "example@gmail.com",
    homeAddress: "Cabuyao City",
    paymentMode: "G-Cash",
    receiptUrl: "#",
    referenceNo: "GCash-REF-000008",
    totalAmount: 800,
    proofFile: "receipt_proof.jpg",
    wantsPrintedReport: null,
    employerName: null,
    assessmentPurpose: null,
    travelType: null,
    hasDiagnosis: null,
    diagnosisFile: null,
    schoolName: null,
    program: null,
    company: null,
    docFiles: null,
    reason: "Psychiatric evaluation request.",
  },

  {
    id: 9,
    serviceClass: "PAC",
    programId: null,
    bookedBy: "client",
    sessionNumber: null,
    totalSessions: null,
    progressionStatus: null,
    disclaimerAccepted: true,
    declineReason: null,
    doctorHistory: null,
    referenceNumber: "PAE-0009-2026-01-25",
    time: "3:00 P.M.",
    date: "January 25, 2026",
    serviceType: "Psychiatric Assessment",
    doctor: "Cristine Lae Erasga",
    type: "Clinic - CMPS",
    status: "Cancelled",
    patientName: "Juan Dela Cruz",
    classification: "Regular",
    sex: "Male",
    dateOfBirth: "09/01/2003",
    contactNumber: "+63 9XXXXXXXXX",
    email: "example@gmail.com",
    homeAddress: "Cabuyao City",
    paymentMode: "Cash",
    receiptUrl: "#",
    referenceNo: null,
    totalAmount: 800,
    proofFile: "receipt_proof.jpg",
    wantsPrintedReport: null,
    employerName: null,
    assessmentPurpose: null,
    travelType: null,
    hasDiagnosis: null,
    diagnosisFile: null,
    schoolName: null,
    program: null,
    company: null,
    docFiles: null,
    reason: "Psychiatric evaluation request.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PAaE APPOINTMENTS
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 10,
    serviceClass: "PAaE",
    programId: null,
    bookedBy: "client",
    sessionNumber: null,
    totalSessions: null,
    progressionStatus: null,
    disclaimerAccepted: true,
    declineReason: null,
    doctorHistory: null,
    referenceNumber: "PREE-0010-2026-03-01",
    time: null,
    date: null,
    serviceType: "Pre-Employment Purpose",
    doctor: "Almie Buco",
    type: "Clinic - CMPS",
    status: "Pending",
    patientName: "Juan Dela Cruz",
    classification: "Regular",
    sex: "Male",
    dateOfBirth: "09/01/2003",
    contactNumber: "+63 9XXXXXXXXX",
    email: "example@gmail.com",
    homeAddress: "Cabuyao City",
    paymentMode: "G-Cash",
    receiptUrl: null,
    referenceNo: "GCash-REF-123456",
    totalAmount: 4500,
    proofFile: "proof_payment.jpg",
    wantsPrintedReport: true,
    employerName: "ABC Corporation",
    assessmentPurpose: "Required for pre-employment psychological screening.",
    travelType: null,
    hasDiagnosis: null,
    diagnosisFile: null,
    schoolName: null,
    program: null,
    company: null,
    docFiles: null,
    reason: null,
  },

  {
    id: 11,
    serviceClass: "PAaE",
    programId: null,
    bookedBy: "client",
    sessionNumber: null,
    totalSessions: null,
    progressionStatus: null,
    disclaimerAccepted: true,
    declineReason: null,
    doctorHistory: null,
    referenceNumber: "VAWC-0011-2026-03-05",
    time: null,
    date: null,
    serviceType: "VAWC Purpose",
    doctor: "Christine Anne Villamarzo",
    type: "Clinic - CMPS",
    status: "Pending",
    patientName: "Juan Dela Cruz",
    classification: "Regular",
    sex: "Female",
    dateOfBirth: "09/01/2003",
    contactNumber: "+63 9XXXXXXXXX",
    email: "example@gmail.com",
    homeAddress: "Cabuyao City",
    paymentMode: "G-Cash",
    receiptUrl: null,
    referenceNo: "GCash-REF-654321",
    totalAmount: 3000,
    proofFile: "proof_vawc.jpg",
    wantsPrintedReport: null,
    employerName: null,
    assessmentPurpose: null,
    travelType: null,
    hasDiagnosis: null,
    diagnosisFile: null,
    schoolName: null,
    program: null,
    company: null,
    docFiles: {
      "Blotter Report": "blotter_report.pdf",
      "Police Report": "police_report.pdf",
    },
    reason: null,
  },

  {
    id: 12,
    serviceClass: "PAaE",
    programId: null,
    bookedBy: "client",
    sessionNumber: null,
    totalSessions: null,
    progressionStatus: null,
    disclaimerAccepted: true,
    declineReason: null,
    doctorHistory: null,
    referenceNumber: "ESA-0012-2026-03-10",
    time: null,
    date: null,
    serviceType: "Emotional Support Animal (ESA) Certification",
    doctor: "Aevon Mustapha",
    type: "Clinic - CMPS",
    status: "Pending",
    patientName: "Juan Dela Cruz",
    classification: "Regular",
    sex: "Male",
    dateOfBirth: "09/01/2003",
    contactNumber: "+63 9XXXXXXXXX",
    email: "example@gmail.com",
    homeAddress: "Cabuyao City",
    paymentMode: "Cash",
    receiptUrl: null,
    referenceNo: null,
    totalAmount: 3000,
    proofFile: "proof_esa.jpg",
    wantsPrintedReport: null,
    employerName: null,
    assessmentPurpose: null,
    travelType: "International",
    hasDiagnosis: true,
    diagnosisFile: "diagnosis_doc.pdf",
    schoolName: null,
    program: null,
    company: null,
    docFiles: null,
    reason: null,
  },

  {
    id: 13,
    serviceClass: "PAaE",
    programId: null,
    bookedBy: "client",
    sessionNumber: null,
    totalSessions: null,
    progressionStatus: null,
    disclaimerAccepted: true,
    declineReason: null,
    doctorHistory: null,
    referenceNumber: "MHCI-0013-2026-03-15",
    time: null,
    date: null,
    serviceType: "Mental Health Certification for Internship",
    doctor: "C. Malabanan",
    type: "Clinic - CMPS",
    status: "Pending",
    patientName: "Juan Dela Cruz",
    classification: "Regular",
    sex: "Male",
    dateOfBirth: "09/01/2003",
    contactNumber: "+63 9XXXXXXXXX",
    email: "example@gmail.com",
    homeAddress: "Cabuyao City",
    paymentMode: "G-Cash",
    receiptUrl: null,
    referenceNo: "GCash-REF-789012",
    totalAmount: 3000,
    proofFile: "proof_internship.jpg",
    wantsPrintedReport: null,
    employerName: null,
    assessmentPurpose: null,
    travelType: null,
    hasDiagnosis: null,
    diagnosisFile: null,
    schoolName: "University of the Philippines",
    program: "BS Psychology",
    company: null,
    docFiles: null,
    reason: null,
  },

  {
    id: 14,
    serviceClass: "PAaE",
    programId: null,
    bookedBy: "client",
    sessionNumber: null,
    totalSessions: null,
    progressionStatus: null,
    disclaimerAccepted: true,
    declineReason: null,
    doctorHistory: null,
    referenceNumber: "WORK-0014-2026-03-20",
    time: null,
    date: null,
    serviceType: "Work-related Purpose",
    doctor: "Almie Buco",
    type: "Online Consultation",
    status: "Pending",
    patientName: "Juan Dela Cruz",
    classification: "Regular",
    sex: "Male",
    dateOfBirth: "09/01/2003",
    contactNumber: "+63 9XXXXXXXXX",
    email: "example@gmail.com",
    homeAddress: "Cabuyao City",
    paymentMode: "G-Cash",
    receiptUrl: null,
    referenceNo: "GCash-REF-345678",
    totalAmount: 3000,
    proofFile: "proof_work.jpg",
    wantsPrintedReport: null,
    employerName: null,
    assessmentPurpose: null,
    travelType: null,
    hasDiagnosis: null,
    diagnosisFile: null,
    schoolName: null,
    program: null,
    company: "XYZ Company",
    docFiles: null,
    reason: null,
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

export const getAppointmentById = (id) =>
  MOCK_APPOINTMENTS.find((apt) => apt.id === parseInt(id));

export const getAppointmentsByStatus = (status) =>
  MOCK_APPOINTMENTS.filter((apt) => apt.status === status);

export const getSessionsByProgram = (programId) =>
  MOCK_APPOINTMENTS.filter((apt) => apt.programId === programId).sort(
    (a, b) => a.sessionNumber - b.sessionNumber,
  );

export const getLatestSession = (programId) => {
  const sessions = getSessionsByProgram(programId);
  return sessions[sessions.length - 1] ?? null;
};

export const getActivePrograms = () => {
  const seen = new Set();
  return MOCK_APPOINTMENTS.filter((apt) => {
    if (!apt.programId || seen.has(apt.programId)) return false;
    seen.add(apt.programId);
    return apt.progressionStatus === "Active";
  });
};

export const canProceedToNextSession = (programId) => {
  const latest = getLatestSession(programId);
  if (!latest) return false;
  return (
    latest.status === "Completed" &&
    latest.progressionStatus === "Active" &&
    latest.sessionNumber < latest.totalSessions
  );
};

export default MOCK_APPOINTMENTS;
